# https://github.com/groundhog2k/helm-charts/blob/master/charts/valkey/RELEASENOTES.md
SESSION_VALKEY_CHART_VERSION: 2.2.5
SESSION_VALKEY_IMAGE_VERSION: 9.0.3
SESSION_VALKEY_REDIS_EXPORTER_IMAGE_VERSION: v1.82.0
SESSION_VALKEY_REPLICAS: 3
