# https://github.com/groundhog2k/helm-charts/blob/master/charts/valkey/RELEASENOTES.md
SESSION_VALKEY_CHART_VERSION: 2.3.4
SESSION_VALKEY_IMAGE_VERSION: "9.0.4@sha256:bdf93f670fdb026eba9e2cf852c3fa8062f92e850fa181626c3b056e83ef04cf"
SESSION_VALKEY_REDIS_EXPORTER_IMAGE_VERSION: "v1.93.0@sha256:6ca518a72f30f7f576ef92963de1b91d3c3f5fd3aeac949f878bfda183587820"
SESSION_VALKEY_REPLICAS: 3
