NEXTCLOUD_REDIRECT_URL: https://nextcloud-brb.schulcloud-verbund.org/apps/files/?dir=/
NEXTCLOUD_BASE_URL: https://nextcloud-brb.schulcloud-verbund.org
BETTERMARKS_APPS_URL: "https://apps.bettermarks.brandenburg.schulcloud-verbund.org"
BETTERMARKS_SCHOOL_URL: "https://school.bettermarks.brandenburg.schulcloud-verbund.org"
ANNOTATIONS: true
RELOADER: true
