apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: legacy-files-cleanup-configmap
    patch: |-
      - op: replace
        path: /data/LEGACY_FILES_SHARED_BUCKET_ROOT_PREFIX
        value: legacy-files/thr
  - target:
      kind: OnePasswordItem
      name: legacy-files-cleanup-s3-secret
    patch: |-
      - op: replace
        path: /spec/itemPath
        value: vaults/sc-dev-thr/items/legacy-files-cleanup-s3
