apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: legacy-files-cleanup-s3-secret
  namespace: sc-common
  labels:
    app: legacy-files-cleanup
spec:
  itemPath: "vaults/sc-dev-cd/items/legacy-files-cleanup-s3"

