TEACHER_STUDENT_VISIBILITY__IS_VISIBLE: "false"
TEACHER_STUDENT_VISIBILITY__IS_CONFIGURABLE: "false"
TEACHER_STUDENT_VISIBILITY__IS_ENABLED_BY_DEFAULT: "true"
TEACHER_VISIBILITY_FOR_EXTERNAL_TEAM_INVITATION: opt-in
STUDENT_TEAM_CREATION: disabled
