apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: sc-common
manifests:
  rawYaml:
    - sc-common.yml
    - sc-openldap-deployment.yml
    - sc-openldap-single-deployment.yml
    - sc-openldap-single-svc.yml
    - sc-openldap-svc.yml
deploy:
  kubectl: {}
  helm:
    releases:
      - name: traffic-manager
        namespace: ambassador
        remoteChart: oci://ghcr.io/telepresenceio/telepresence-oss
        version: 2.28.0
        createNamespace: true
        setValues:
          image.registry: ghcr.io/telepresenceio
        valuesFiles:
          - telepresence-traffic-manager/values.yaml
profiles:
  - name: dbc
    manifests:
      kustomize:
        paths:
          - namespace-activator/overlays/dbc
          - legacy-files-cleanup/overlays/dbc

  - name: brb
    manifests:
      kustomize:
        paths:
          - namespace-activator/overlays/brb
          - legacy-files-cleanup/overlays/brb

  - name: nbc
    manifests:
      kustomize:
        paths:
          - namespace-activator/overlays/nbc
          - legacy-files-cleanup/overlays/nbc

  - name: thr
    manifests:
      kustomize:
        paths:
          - namespace-activator/overlays/thr
          - legacy-files-cleanup/overlays/thr

